### ISSUE TITLE
A mutlitude of issues on two NEW3DS systems.

### ISSUE THREAD

**Issue by JamesIsWack** [windows-server-2003/ThirdTube#131]
Hello,
I have recently had various issues with the Thirdtube app. 
1) Videos not loading/skipping every two seconds
2) Videos not loading for subscribed channels on the Channels page
3) some MINOR crashes that happen randomly after two or so hours using the app

**Comment by shadow8493** [comment]
Same things are happening to the old3ds

**Comment by JamesIsWack** [comment]
> Same things are happening to the old3ds

yeah... i think is a Youtube thing, since they have changed a lot of stuff. as of right now i just use the web browser, works fine

**Comment by windows-server-2003** [comment]
The first two should be fixed in the latest release.
For the third one, could you try to find a way to reproduce it?

**Comment by JamesIsWack** [comment]
> The first two should be fixed in the latest release. For the third one, could you try to find a way to reproduce it?

sometimes if i scrub thru the video too fast, it stops loading video information, then crashes after awhile.

**Comment by cooolgamer** [comment]
1. Doesn't happen on my old 3ds on latest version v0.5.2 so it seems to be fixed
2. Fixed in 0.5.1
3. Still happens yeah

**Comment by pyra9345** [comment]
3 also happens to me however (this might be chance, i rarely use my o3ds for yt) but on my o3ds it crashes less than on my n3dsxl
