### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shadow8493** [windows-server-2003/ThirdTube#158]
There is a error when i try to watch a video
![16741601457279051572201237311157](https://user-images.githubusercontent.com/83465567/213553062-b6ea5bd7-5173-43d8-9511-cbf3e4559ed3.jpg)

**Comment by windows-server-2003** [comment]
Is it fixed now? I made a fix that does not require an update.

**Comment by BZHDeveloper** [comment]
Error still occurs, same description and code. Except this time it's a [a+v] error.

Version : v0.5.2
Video for testing : https://youtu.be/H-lRX9SQ4CM

**Comment by shadow8493** [comment]
Its still the same error

**Comment by shadow8493** [comment]
> Is it fixed now? I made a fix that does not require an update.

Its still the same error

**Comment by cooolgamer** [comment]
same error on some videos here

**Comment by Jelte2357** [comment]
I now have the error on every video I watch, 0xfffffffa, tested about 20 videos

**Comment by Aspenpaw** [comment]
It no longer appears to be an issue for me. If you've done something, it seems to have worked for someone at least, thanks! :D
