### ISSUE TITLE
Videos don't load.

### ISSUE THREAD

**Issue by 6ell** [windows-server-2003/ThirdTube#181]
I can't say why they don't. Here's log. Maybe it's not something with app itself.
![2023-08-08_20-52-12 629_top](https://github.com/windows-server-2003/ThirdTube/assets/118050160/1842bc91-1bb7-427b-8799-203c3a1b28a7)

**Comment by windows-server-2003** [comment]
Should be fixed. Sorry for long period of unavailability.

**Comment by 6ell** [comment]
I don't know why, but the problem is back now.
![2024-04-03_19-10-47 700_top](https://github.com/windows-server-2003/ThirdTube/assets/118050160/8a68d94a-42c1-4f5e-843e-b683a2fd7235)
